### ISSUE TITLE
Things to Update

### ISSUE THREAD

**Issue by rramaker** [HudsonAlpha/aRNAPipe#1]
1.) Output insert size form picard tools
2.) Output Kallisto alignment stats
3.) Document Star alignment stats headers (what's the difference between multimapped v. ambiguous and what is total counts?)
4.) Document header in Star results output (there's three columns and no headers)
5.) Add splicing quantification
6.) Add work around to prevent spyder from erroring if 0 reads align in a sample (I think PCA is erroring).

**Comment by arnald-alonso** [comment]
Hey Ryne, could you provide a path to a dataset (samples file and config) where I can reproduce the error described in point 6? I'll start with points 2 and 6.
