### ISSUE TITLE
How make the result showed by gene name rather than Ensembl ID

### ISSUE THREAD

**Issue by huangwentao1996** [HudsonAlpha/aRNAPipe#5]
Hi,

I used Ensembl GRC38 sequence and gtf file as the reference to build genome reference. But when I use the reference built to process the data, I found the gene count and exon count generated are listed by Ensembl ID rather than gene and exon name. Could you tell me how to make them listed by gene name?

Thanks!
Wentao

**Comment by arnald-alonso** [comment]
Hi Wentao,

Output files use Ensembl ID because it is a canonical and unique code, more appropriate than gene name to unequivocally identify gene features. You can use the gtf file to extract gene names using a simple script or Biomart.

**Comment by huangwentao1996** [comment]
Hi,

Thanks for your reply. It is true that Ensemble ID is more accurate than gene name. But sometimes we don't focus on the variation of transcript isoforms, so I wonder if there is option in HTseq that can can specify the gene name as output rather than Ensembl ID. If we use another script or biomart to convert them to gene name and merge the count number, it takes some time, it would be better that there is a direct option that specify gene name as an output.

Thanks!
Wentao

**Comment by arnald-alonso** [comment]
Hi,

Take into account that htseq provides options for gene and exon
quantification. Both options are available from aRNApipe. In fact, htseq
recommends to quantify at the exon level rather than at transcript level
and then using DEXseq for differential transcript analysis. Take also into
account that Ensemble IDs may be referencing genes or exons depending on
the performed analysis (htseq-gene or htseq-exon). As far as I know HTseq
has no options for switching to gene name instead of Ensembl ID.

2016-08-11 20:15 GMT+02:00 huangwentao1996 <notifications@github.com>:

**Comment by huangwentao1996** [comment]
Hi,

I found there is a option for HTSeq to generate the count matrix by gene name, which can be accomplished by specifying feature type to be gene_name. http://www-huber.embl.de/HTSeq/doc/count.html.
I also wonder how do you generate the rpkm for ht-gene count result. because every geneID can match gene, exon, transcript and CDS in the gtf file. So which one do you choose as the length for normalization?

Wentao

**Comment by arnald-alonso** [comment]
Hi,

Thanks for your comments and suggestions. Regarding to the generation of a
count matrix by gene name this is not possible using only htseq. Take into
account that the feature type option refers to the type of features that
will be used to align reads (3rd column of the gtf file). In the common
htseq-gene analysis, feature type is set to 'exon' and 'idattr' to gene_id.
Under this configuration reads are aligned to exons and the resulting exon
counts are aggregated by gene id to get the gene counts. This is linked to
your second comment, aRNApipe computes gene length for rpkm by adding all
the gene exon lengths, taking into account overlapping exon regions only
one time. This is the common and recommended approach taking into account
the way htseq aligns reads under this configuration.

2016-08-22 21:56 GMT+02:00 huangwentao1996 <notifications@github.com>:
